name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:

  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: npm run start
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
          INSTAGRAM_GRAPH_API_VERSION: v24.0
      - run: |
          git config user.name baumannzone
          git config user.email jorge.baumann.aguilar@gmail.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[Bot] Update README.md"
          git push origin master
